name: CI

on:
    [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: sudo apt install -y cmake ligtest-dev

            - name: Configure
              run: cmake -S . -B build --fresh -DCPACK_GENERATOR=DEB -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug

            - name: Build
              run: cmake --build build

            - name: Testing
              run: ctest --test-dir build --output-on-failure

            - name: Packaging
              run: cmake --build build --target package

            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: build/*.deb
